In [1]:
import torch
import pandas as pd
import matplotlib as plt
import numpy as np

In [2]:
print(torch.__version__)

2.1.0.post100


## Create a Tensor

a multi-dimensional matrix containing elements of a single data type.

See [tensor product doc.](https://pytorch.org/docs/stable/tensors.html)

In [3]:
scalar = torch.tensor(7)
scalar.ndim
scalar.item()

7

In [4]:
vector= torch.tensor([3,4])
vector.ndim
vector.shape

torch.Size([2])

In [5]:
matrix=torch.tensor([[3,4],[2,9]])
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [6]:
t=torch.tensor([[[1,2,3],[6,7,8],[9,0,1]]])
t.shape

torch.Size([1, 3, 3])

In [7]:
t=torch.rand(3,5)
t

tensor([[0.6289, 0.9684, 0.1055, 0.6834, 0.8477],
        [0.9838, 0.7761, 0.6251, 0.4676, 0.9500],
        [0.6978, 0.0770, 0.3767, 0.2512, 0.5455]])

### Create a random tensor of an image

In [8]:
t_i = torch.rand(size=(224,224,3)) # height, width, color channels(RGB)
t_i

tensor([[[0.0617, 0.3622, 0.6623],
         [0.6535, 0.5442, 0.2277],
         [0.0625, 0.1328, 0.3120],
         ...,
         [0.4195, 0.5974, 0.9434],
         [0.5845, 0.1131, 0.9866],
         [0.0022, 0.0235, 0.9700]],

        [[0.1797, 0.5300, 0.4461],
         [0.5466, 0.7143, 0.0895],
         [0.4389, 0.0614, 0.2932],
         ...,
         [0.5349, 0.4867, 0.2012],
         [0.3910, 0.1347, 0.2676],
         [0.9820, 0.8290, 0.7307]],

        [[0.8865, 0.7992, 0.8803],
         [0.5898, 0.9005, 0.5529],
         [0.0164, 0.8587, 0.5098],
         ...,
         [0.3973, 0.5512, 0.5129],
         [0.1416, 0.6074, 0.7414],
         [0.2460, 0.9973, 0.7144]],

        ...,

        [[0.1235, 0.1150, 0.0198],
         [0.6394, 0.6734, 0.9931],
         [0.1777, 0.2758, 0.1070],
         ...,
         [0.6815, 0.9810, 0.3218],
         [0.8851, 0.5549, 0.1551],
         [0.5234, 0.9459, 0.0925]],

        [[0.0761, 0.2403, 0.1221],
         [0.3970, 0.0178, 0.9707],
         [0.

In [9]:
zeros = torch.zeros(size=(2,3))
zeros
ones= torch.ones(2,3)

In [10]:
ones*zeros


tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Range of values

In [11]:
t=torch.arange(1,11)
t


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
torch.arange(start=0, end=1000,step=77)


tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [13]:
t=torch.tensor([[[1,2,3],[6,7,8],[9,0,1]]], dtype=torch.float16,device="cpu")
t.dtype

torch.float16

In [15]:
b=torch.tensor([[[1.,2.,3.],[6.,7.,8.],[9.,0,1.]]])
b.dtype

torch.float32

In [16]:
b*t

tensor([[[ 1.,  4.,  9.],
         [36., 49., 64.],
         [81.,  0.,  1.]]])

In [18]:
# Addition
t + 10


tensor([[[11., 12., 13.],
         [16., 17., 18.],
         [19., 10., 11.]]], dtype=torch.float16)

In [19]:
# multiple by
t * 2

tensor([[[ 2.,  4.,  6.],
         [12., 14., 16.],
         [18.,  0.,  2.]]], dtype=torch.float16)

In [25]:
# Matrix multiplication: inner dimensions need to match, and the new result dimensions = outter dimension

a=torch.tensor([[2,3,4],[1,1,3]])
b=torch.tensor([[2,3],[1,1],[3,3]])
a.matmul(b)

UsageError: Line magic function `%%time` not found.


In [27]:
# Transpose to change the shape
a

tensor([[2, 3, 4],
        [1, 1, 3]])

In [28]:
a.T

tensor([[2, 1],
        [3, 1],
        [4, 3]])

In [30]:
# min
a.min()

tensor(1)

In [35]:
# to get the mean we need float type
torch.mean(a.type(torch.float16)), a.type(torch.float16).mean()

(tensor(2.3340, dtype=torch.float16), tensor(2.3340, dtype=torch.float16))

In [37]:
# index position
b=torch.rand(size=(1,10))
b

tensor([[0.1535, 0.6610, 0.7830, 0.0669, 0.5836, 0.7432, 0.7166, 0.8276, 0.7303,
         0.1960]])

In [38]:
b.argmin(),b.argmax()

(tensor(3), tensor(7))