In [1]:
import torch
import pandas as pd
import matplotlib as plt
import numpy as np

In [2]:
print(torch.__version__)

2.1.0.post100


## Create a Tensor

a multi-dimensional matrix containing elements of a single data type.

See [tensor product doc.](https://pytorch.org/docs/stable/tensors.html)

In [3]:
scalar = torch.tensor(7)
scalar.ndim
scalar.item()

7

In [4]:
vector= torch.tensor([3,4])
vector.ndim
vector.shape

torch.Size([2])

In [5]:
matrix=torch.tensor([[3,4],[2,9]])
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [6]:
t=torch.tensor([[[1,2,3],[6,7,8],[9,0,1]]])
t.shape

torch.Size([1, 3, 3])

In [7]:
t=torch.rand(3,5)
t

tensor([[0.9616, 0.6920, 0.2361, 0.1282, 0.0052],
        [0.6863, 0.7579, 0.5905, 0.7452, 0.3609],
        [0.2110, 0.6885, 0.0075, 0.3114, 0.2991]])

### Create a random tensor of an image

In [8]:
t_i = torch.rand(size=(224,224,3)) # height, width, color channels(RGB)
t_i

tensor([[[0.8678, 0.8700, 0.2760],
         [0.1654, 0.0562, 0.4003],
         [0.8080, 0.8386, 0.5690],
         ...,
         [0.9458, 0.5165, 0.1726],
         [0.9352, 0.8694, 0.4310],
         [0.7862, 0.9366, 0.8179]],

        [[0.3449, 0.5224, 0.3700],
         [0.3186, 0.3666, 0.3693],
         [0.9371, 0.4125, 0.8357],
         ...,
         [0.7558, 0.3118, 0.5471],
         [0.9051, 0.7419, 0.9815],
         [0.8880, 0.8071, 0.1233]],

        [[0.7458, 0.7954, 0.6438],
         [0.3478, 0.8423, 0.4235],
         [0.7907, 0.8931, 0.6702],
         ...,
         [0.9723, 0.3282, 0.5871],
         [0.4357, 0.2247, 0.6385],
         [0.3845, 0.8664, 0.4561]],

        ...,

        [[0.4331, 0.6559, 0.4292],
         [0.2234, 0.3131, 0.8144],
         [0.7251, 0.9570, 0.0108],
         ...,
         [0.6979, 0.0994, 0.0810],
         [0.9071, 0.9174, 0.7570],
         [0.6809, 0.0995, 0.5989]],

        [[0.8903, 0.4448, 0.6556],
         [0.9036, 0.5387, 0.4692],
         [0.

In [9]:
zeros = torch.zeros(size=(2,3))
zeros
ones= torch.ones(2,3)

In [10]:
ones*zeros


tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Range of values

In [11]:
t=torch.arange(1,11)
t


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
torch.arange(start=0, end=1000,step=77)


tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [13]:
t=torch.tensor([[[1,2,3],[6,7,8],[9,0,1]]], dtype=torch.float16,device="cpu")
t.dtype

torch.float16

In [14]:
b=torch.tensor([[[1.,2.,3.],[6.,7.,8.],[9.,0,1.]]])
b.dtype

torch.float32

In [15]:
b*t

tensor([[[ 1.,  4.,  9.],
         [36., 49., 64.],
         [81.,  0.,  1.]]])

In [16]:
# Addition
t + 10


tensor([[[11., 12., 13.],
         [16., 17., 18.],
         [19., 10., 11.]]], dtype=torch.float16)

In [17]:
# multiple by
t * 2

tensor([[[ 2.,  4.,  6.],
         [12., 14., 16.],
         [18.,  0.,  2.]]], dtype=torch.float16)

In [18]:
# Matrix multiplication: inner dimensions need to match, and the new result dimensions = outter dimension

a=torch.tensor([[2,3,4],[1,1,3]])
b=torch.tensor([[2,3],[1,1],[3,3]])
a.matmul(b)

tensor([[19, 21],
        [12, 13]])

In [19]:
# Transpose to change the shape
a

tensor([[2, 3, 4],
        [1, 1, 3]])

In [20]:
a.T

tensor([[2, 1],
        [3, 1],
        [4, 3]])

In [21]:
# min
a.min()

tensor(1)

In [22]:
# to get the mean we need float type
torch.mean(a.type(torch.float16)), a.type(torch.float16).mean()

(tensor(2.3340, dtype=torch.float16), tensor(2.3340, dtype=torch.float16))

In [23]:
# index position
b=torch.rand(size=(1,10))
b

tensor([[0.9325, 0.7086, 0.4639, 0.7003, 0.5913, 0.2466, 0.8547, 0.3211, 0.9524,
         0.2946]])

In [24]:
b.argmin(),b.argmax()

(tensor(5), tensor(8))

## Reshaping, stacking, squeezing and unsqueezing

In [28]:
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [46]:
# reshape to compatible shape. Add one dimension with same size as original tensor. Two ways to do so:
x_r = x.reshape(1,9)
x_r = torch.reshape(x,(1,9))
x_r, x_r.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [32]:
# Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
x_v = x.view(1,9)
x_v, x_v.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [35]:
# stack of tensors, like a concatenation
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [43]:
# squeeze to remove one dim
z=x.squeeze()
z, z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
z=x.unsqueeze(dim=1)  # dim is between -2 and 1
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [55]:
# Permute dimensions (it returns a view)
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [77]:
# indexing a tensor - uses the same as NumPy
x=torch.arange(1,16).reshape(1,3,5)
print(x,x.shape)

print(x[0,0,0])
print(x[0][1][0])
print(x[0][:][1]) # : to get of a single dimension
print(x[0,2,4])

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]]) torch.Size([1, 3, 5])
tensor(1)
tensor(6)
tensor([ 6,  7,  8,  9, 10])
tensor(15)


## NumPy to Pytorch Tensor

In [79]:
a = np.arange(1.0,8.0)  # type is float 64
t = torch.from_numpy(a)
a,t

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [81]:
t =torch.from_numpy(a).type(torch.float32)
t.dtype

torch.float32

In [84]:

b=t.numpy()
t=t+1
b,t

(array([2., 3., 4., 5., 6., 7., 8.], dtype=float32),
 tensor([3., 4., 5., 6., 7., 8., 9.]))

In [87]:
# Run on GPUs
if torch.backends.mps.is_available():
   mps_device = torch.device("mps")
   x = torch.ones(1, device=mps_device)
   print (x)
else:
   print ("MPS device not found.")

tensor([1.], device='mps:0')


In [89]:
import time
start_time = time.time()

# syncrocnize time with cpu, otherwise only time for oflaoding data to gpu would be measured
torch.mps.synchronize()

a = torch.ones(4000,4000, device="mps")
for _ in range(200):
   a +=a

elapsed_time = time.time() - start_time
print( "GPU Time: ", elapsed_time)

GPU Time:  0.5641310214996338


In [92]:
# Exercise 1: random tensor shape 7,7
t= torch.rand([7,7])
t,t.shape

(tensor([[0.3885, 0.8617, 0.8685, 0.1506, 0.6697, 0.4213, 0.8585],
         [0.3847, 0.3596, 0.5139, 0.4218, 0.7892, 0.2825, 0.4766],
         [0.3784, 0.1834, 0.5558, 0.4238, 0.1246, 0.2212, 0.0377],
         [0.0377, 0.8175, 0.3430, 0.6210, 0.8896, 0.2128, 0.6732],
         [0.7269, 0.0581, 0.9083, 0.0258, 0.1281, 0.6161, 0.3876],
         [0.9179, 0.9741, 0.5860, 0.1795, 0.4625, 0.2965, 0.4824],
         [0.8445, 0.6060, 0.0409, 0.9720, 0.0958, 0.2600, 0.9514]]),
 torch.Size([7, 7]))

In [96]:
# multiple by another tensor shape 1,7
t2=torch.arange(1,8)
t*t2

tensor([[0.3885, 1.7234, 2.6056, 0.6025, 3.3487, 2.5278, 6.0097],
        [0.3847, 0.7191, 1.5416, 1.6872, 3.9460, 1.6948, 3.3359],
        [0.3784, 0.3669, 1.6675, 1.6950, 0.6232, 1.3274, 0.2641],
        [0.0377, 1.6351, 1.0289, 2.4842, 4.4480, 1.2768, 4.7127],
        [0.7269, 0.1163, 2.7250, 0.1031, 0.6407, 3.6966, 2.7135],
        [0.9179, 1.9483, 1.7581, 0.7178, 2.3123, 1.7792, 3.3768],
        [0.8445, 1.2120, 0.1226, 3.8880, 0.4789, 1.5598, 6.6597]])

In [103]:
# Set the random seed to 0 and do 2 & 3 over again
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)
t1=torch.rand([7,7])
t2=torch.rand([1,7]).T
t1.matmul(t2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
# multiple on GPU

In [111]:
t1=torch.mps.manual_seed(seed=1234)
mps_device = torch.device("mps")
t1=torch.rand([2,3],device=mps_device)
t2=torch.rand([2,3],device=mps_device).T
t3=t1.matmul(t2)
t3

tensor([[0.9868, 1.7565],
        [0.6685, 1.2782]], device='mps:0')

In [112]:
torch.min(t3),torch.max(t3)

(tensor(0.6685, device='mps:0'), tensor(1.7565, device='mps:0'))

In [113]:
torch.argmin(t3),torch.argmax(t3)

(tensor(2, device='mps:0'), tensor(1, device='mps:0'))

In [123]:
t1=torch.manual_seed(seed=7)
t1=torch.rand([1,1,1,10])
t1,t1.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [130]:
t2=t1.squeeze()
t2,t2.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))